# Generated by Django 4.2.16 on 2026-08-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='application_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jobposition',
            old_name='posted_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='applied_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='requirements',
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.candidate'),
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='candidates',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='jobposition',
            table='job_positions',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resumes',
        ),
    ]
